apiVersion: v1
kind: Pod
metadata:
  labels:
    component: cloud-controller-manager
    tier: control-plane
  name: cloud-controller-manager
  namespace: kube-system
spec:
  containers:
  - name: cloud-controller-manager
    image: docker.io/k8scloudprovider/openstack-cloud-controller-manager:${OPENSTACK_CLOUD_CONTROLLER_MANAGER_VERSION}
    command:
    - openstack-cloud-controller-manager
    - --v=2
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --use-service-account-credentials=true
    - --cloud-config=/etc/kubernetes/openstack.conf
    - --cloud-provider=openstack   # Add your own cloud provider here!
    volumeMounts:
      - mountPath: /etc/ssl/certs
        name: ca-certs
        readOnly: true
      - mountPath: /etc/kubernetes/pki
        name: k8s-certs
        readOnly: true
      - mountPath: /etc/kubernetes/controller-manager.conf
        name: kubeconfig
        readOnly: true
      - mountPath: /etc/kubernetes/openstack.conf
        name: openstack-configuration
        readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/controller-manager.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /etc/kubernetes/openstack.conf
      type: FileOrCreate
    name: openstack-configuration
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs